### PR TITLE
Support multiple k8s version for a release of coredns

### PR DESCRIPTION
**Pull request by rajansandeep**
This is applicable currently if k8s 1.15 continues to have CoreDNS 1.3.1

### CODE REVIEW

**Comment by chrisohaver** [comment]
Lets wait on this one... For one, we don't know where the k8s/coredns/cos conundrum is going to land yet.  Also,  If the e2e tests stays at 1.5.0, and kubeadm sticks with 1.3.1, this does not implicitly validate both versions for use with k8s 1.15 clusters.   I suppose it depends on how the tests are divided - what kind of tests are done using kubeup clusters, and which tests are done using kubeadm clusters?

I am assuming tests in kubeadm clusters are mainly about kubeadm itself, and that the other more general tests (dns conformance, scalability, etc), are done on kubeup clusters. Is that right?

**Comment by rajansandeep** [comment]
>I am assuming tests in kubeadm clusters are mainly about kubeadm itself, and that the other more general tests (dns conformance, scalability, etc), are done on kubeup clusters. Is that right?

Correct. All the general tests use kube-up. 


>Lets wait on this one... For one, we don't know where the k8s/coredns/cos conundrum is going to land yet. Also, If the e2e tests stays at 1.5.0, and kubeadm sticks with 1.3.1, this does not implicitly validate both versions for use with k8s 1.15 clusters. 

If in case kube-up remains to have 1.5.0 for 1.15, what do we indicate as the "official" coredns version for k8s 1.15?

**Comment by chrisohaver** [comment]
>If in case kube-up remains to have 1.5.0 for 1.15, what do we indicate as the "official" coredns version for k8s 1.15?

It would be 1.5.0.

**Comment by rajansandeep** [comment]
I guess this PR can be merged now.

**Comment by chrisohaver** [comment]
`k8sRelease` -> `k8sReleases` and i think we're good.

**Pull request merged**
