### PR TITLE
Fill in remaining supported CoreDNS versions

### PR DESCRIPTION
**Pull request by rajansandeep**
- [x] Add versions of CoreDNS (up to 1.2.2) supported till k8s v1.12
- [x] Add versions of CoreDNS (up to 1.1.3) supported till k8s v1.11

Also, adds the `log` plugin to the list of supported plugins.

### CODE REVIEW

**Comment by chrisohaver** [comment]
>  I have omitted coredns v1.2.3 since the kubernetes plugin was broken in that version.

This also means that you cannot migrate _from_ 1.2.3.

**Comment by chrisohaver** [comment]
For the first version (1.1.3), you just need to be able to migrate from that version, not to it...
That means it doesn't need to contain the plugins definition.

**Comment by chrisohaver** [comment]
For the first version (1.1.3), you just need to be able to migrate from that version, not to it...
That means it doesn't need to contain the plugins definition.

**Comment by rajansandeep** [comment]
@chrisohaver this is now completed with up to CoreDNS 1.1.3 supported.

**Comment by chrisohaver** [comment]
> completed with up to CoreDNS 1.1.3 supported 

Thanks.  Up _from_ 1.1.3.  Can't go to 1.1.3, but that's as expected.

**Pull request merged**
