### PR TITLE
Add circleci for testing k8s-deployment

### PR DESCRIPTION
**Pull request by rajansandeep**
This PR adds CircleCI to enable the k8s-deployment integration tests from the coredns/ci repo.

### CODE REVIEW

**Comment by chrisohaver** [comment]
@miekg, can you enable circleci for this this repo? thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] Add circle..." ]
>@miekg, can you enable circleci for this this repo? thanks!

I think this should already work. I don't see new buttons in circleci to enable 
this repo...

**Comment by rajansandeep** [comment]
@miekg You can add the deployment and ci repo from here:
https://circleci.com/add-projects/gh/coredns

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] Add circle..." ]
>@miekg You can add the deployment and ci repo from here:
>https://circleci.com/add-projects/gh/coredns

done

**Pull request merged**
