### PR TITLE
Run make with -e so users can override makefile variables

### LINKED ISSUE #267: Is there an easy way to build a specific version?
Right now `VERSION` is set dynamically to the latest release on github. Is there an easy way to build an older one? Right now I'm having to modify `debian/rules` to add `-e` to `make` in the shebang so I can set `VERSION` as an env var.

Is there an easier way to do this?

### PR DESCRIPTION
**Pull request by kaysond**
Fixes #267

### CODE REVIEW

**Comment by chrisohaver** [comment]
@utkonos, Do you have any concern for the existing variables being somewhat generic?  For example `VERSION` is more likely to be already in use on a system than something like `DPKG_COREDNS_VERSION`

**Comment by utkonos** [comment]
That is a good point. There is no reason the variables used here can't be more unique rather than more generic. Making them more unique would prevent a collision with a potentially common variable like `VERSION`. I think that's a good modification. @kaysond can you make that edit to the PR?

**Comment by kaysond** [comment]
Done! I changed `VERSION` and `DISTRIBUTION` since that also seemed like one that might be set errantly.

Tested the build on latest and 1.9.1.

**Comment by chrisohaver** [comment]
Thanks all!

**Pull request merged**
