### PR TITLE
Adding pod anti-affinity to the deployment manifest.

### LINKED ISSUE #49: kubernetes: Add pod anti node affinity
Add pod anti node affinity, now that there are 2 replicas.

### PR DESCRIPTION
**Pull request by swade1987**
Closes #49

### CODE REVIEW

**Comment by willvrny** [comment]
I like the use of preferred as it will cover the case of a single worker node.

**Comment by chrisohaver** [comment]
Lgtm. Thanks! /integration

**Comment by chrisohaver** [comment]
A similar change was recently rejected/reverted in kubernetes main repo ... looks like for scalability problems with pod affinity. kubernetes/kubernetes#52193

But looks like these scale issues may have been fixed since then ... kubernetes/kubernetes#54189

... and then followed up by a PR to add it back ... kubernetes/kubernetes#57683 ... the specific details still being discussed in that PR (namely preferred vs required).

**Pull request merged**
