### PR TITLE
Remove support for federation in deploy script

### LINKED ISSUE #222: Remove support for deprecated federation
With the removal of federation from coredns plugins in  <https://github.com/coredns/coredns/issues/3041>, I suspect similar removal is needed from this repo, specifically all of the code from #100 and some of the code in #85.

### PR DESCRIPTION
**Pull request by rajansandeep**
Fixes #222

### CODE REVIEW

**Comment by rajansandeep** [comment]
@chrisohaver Do we need to revert changes from #100 as well?

**Comment by chrisohaver** [comment]
> @chrisohaver Do we need to revert changes from #100 as well?

Yeah. See #222...

**Comment by chrisohaver** [comment]
I can’t re-run the ci, because it ran in your account (circleci magic)

**Comment by rajansandeep** [comment]
yeah :/ 
updating my fork to reflect changes and I'll trigger the re-run

**Pull request merged**
